[clog]
link-style = "github"
changelog = "CHANGELOG.md"
repository = "https://github.com/brianp/muxed"
from-latest-tag = true

[sections]
Features = ["feat"]
Performance = ["perf"]
Improvements = ["impr", "im", "imp"]
Documentation = ["docs"]
Deprecations = ["depr"]
Examples = ["examples"]
Refactor = ["ref", "refactor", "chore"]
Fixes = ["fix", "test"]
Style = ["style"]
