[clog]
link-style = "github"
changelog = "CHANGELOG.md"

[sections]
Performance = ["perf"]
Improvements = ["impr", "im", "imp"]
Documentation = ["docs"]
Deprecations = ["depr"]
Examples = ["examples"]
Refactor = ["ref", "refactor"]
