language: rust
cache: cargo

rust:
  - nightly

matrix:
  allow_failures:
    - env: TMUX_VERSION=master
    - env: TMUX_VERSION=1.9a
  exclude:
    - os: osx
      env: TMUX_VERSION=2.7
    - os: osx
      env: TMUX_VERSION=2.6
    - os: osx
      env: TMUX_VERSION=2.5
    - os: osx
      env: TMUX_VERSION=2.4
    - os: osx
      env: TMUX_VERSION=2.3
    - os: osx
      env: TMUX_VERSION=2.2
    - os: osx
      env: TMUX_VERSION=2.1
    - os: osx
      env: TMUX_VERSION=2.0
    - os: osx
      env: TMUX_VERSION=1.9a
    - os: osx
      env: TMUX_VERSION=1.8

env:
  - TMUX_VERSION=master
  - TMUX_VERSION=2.8
  - TMUX_VERSION=2.7
  - TMUX_VERSION=2.6
  - TMUX_VERSION=2.5
  - TMUX_VERSION=2.4
  - TMUX_VERSION=2.3
  - TMUX_VERSION=2.2
  - TMUX_VERSION=2.1
  - TMUX_VERSION=2.0
  - TMUX_VERSION=1.9a
  - TMUX_VERSION=1.8

os:
  - linux
  - osx

before_script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
        sudo apt-get remove tmux && sudo apt-get install libevent-dev;
    fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
        brew update;
    fi
  - git clone https://github.com/tmux/tmux.git tmux
  - cd tmux
  - git checkout $TMUX_VERSION
  - sh autogen.sh
  - ./configure --prefix=$HOME/tmux && make && make install
  - export PATH=$PATH:$HOME/tmux/bin
  - cd ..
  - tmux -V

notifications:
  email: false
