language: rust
cache: cargo

git:
  depth: 1

rust:
  - stable
  - beta
  - nightly

script: cargo test --workspace

matrix:
  allow_failures:
    - env: TMUX_VERSION=master
    - env: TMUX_VERSION=2.9a
    - env: TMUX_VERSION=2.8
    - rust: beta
    - rust: nightly
  exclude:
    - os: osx
      env: TMUX_VERSION=2.9a
    - os: osx
      env: TMUX_VERSION=2.8
    - os: osx
      rust: nightly
    - os: osx
      rust: beta
    - os: linux
      rust: beta
      env: TMUX_VERSION=master
    - os: linux
      rust: beta
      env: TMUX_VERSION=2.9a
    - os: linux
      rust: beta
      env: TMUX_VERSION=2.8
    - os: linux
      rust: nightly
      env: TMUX_VERSION=master
    - os: linux
      rust: nightly
      env: TMUX_VERSION=2.9a
    - os: linux
      rust: nightly
      env: TMUX_VERSION=2.8

env:
  - TMUX_VERSION=master
  - TMUX_VERSION=3.0a
  - TMUX_VERSION=2.9a
  - TMUX_VERSION=2.8

os:
  - linux
  - osx

before_script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
        sudo apt-get remove tmux && sudo apt-get install libevent-dev;
    fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
        brew update;
    fi
  - git clone https://github.com/tmux/tmux.git tmux
  - cd tmux
  - git checkout $TMUX_VERSION
  - sh autogen.sh
  - ./configure --prefix=$HOME/tmux && make && make install
  - export PATH=$PATH:$HOME/tmux/bin
  - cd ..
  - tmux -V

notifications:
  email: false
