language: rust
cache: cargo

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
    - env: TMUX_VERSION=master
    - env: TMUX_VERSION=1.9a
  exclude:
    - rust: nightly
      env: TMUX_VERSION=master
    - rust: nightly
      env: TMUX_VERSION=2.2
    - rust: nightly
      env: TMUX_VERSION=2.1
    - rust: nightly
      env: TMUX_VERSION=2.0
    - rust: nightly
      env: TMUX_VERSION=1.9a
    - os: osx
      rust: nightly
    - os: osx
      rust: beta
    - os: osx
      env: TMUX_VERSION=master
    - os: osx
      env: TMUX_VERSION=2.2
    - os: osx
      env: TMUX_VERSION=2.1
    - os: osx
      env: TMUX_VERSION=2.0
    - os: osx
      env: TMUX_VERSION=1.9a
    - os: osx
      env: TMUX_VERSION=1.8

env:
  - TMUX_VERSION=master
  - TMUX_VERSION=2.3
  - TMUX_VERSION=2.2
  - TMUX_VERSION=2.1
  - TMUX_VERSION=2.0
  - TMUX_VERSION=1.9a
  - TMUX_VERSION=1.8

os:
  - linux
  - osx

before_script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
        sudo apt-get remove tmux;
    fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
        brew update && brew install libevent;
    fi
  - git clone https://github.com/tmux/tmux.git tmux
  - cd tmux
  - git checkout $TMUX_VERSION
  - sh autogen.sh
  - ./configure --prefix=$HOME/tmux && make && make install
  - export PATH=$PATH:$HOME/tmux/bin
  - cd ..
  - tmux -V

notifications:
  email: false
