language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

env:
  - ARCH=x86_64
  - ARCH=i686

os:
  - linux
  #- osx

addons:
  apt:
    packages:
      - tmux

notifications:
  email: false
