language: rust
cache: cargo

rust:
  - nightly

matrix:
  allow_failures:
    - env: TMUX_VERSION=master
    - env: TMUX_VERSION=2.8
    - env: TMUX_VERSION=2.7
  exclude:
    - os: osx
      env: TMUX_VERSION=2.8

env:
  - TMUX_VERSION=master
  - TMUX_VERSION=2.9a
  - TMUX_VERSION=2.8
  - TMUX_VERSION=2.7

os:
  - linux
  - osx

before_script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
        sudo apt-get remove tmux && sudo apt-get install libevent-dev;
    fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
        brew update;
    fi
  - git clone https://github.com/tmux/tmux.git tmux
  - cd tmux
  - git checkout $TMUX_VERSION
  - sh autogen.sh
  - ./configure --prefix=$HOME/tmux && make && make install
  - export PATH=$PATH:$HOME/tmux/bin
  - cd ..
  - tmux -V

notifications:
  email: false
