[package]
name = "muxed"
version = "0.5.0" #:version
authors = ["Brian Pearce"]

[dependencies]
libc            = "0.2.21"
yaml-rust       = { version = "0.3.2", default-features = false }
docopt          = "0.7"
rustc-serialize = "0.3"

[dev-dependencies]
rand      = "0.3.15"
regex     = "0.2.1"
