[package]
name = "muxed"
version = "0.4.0"
authors = ["Brian Pearce"]

[dependencies]
clap      = { version = "2.5.1", default-features = false }
libc      = "0.2.10"
yaml-rust = "0.3.2"

[dev-dependencies]
rand      = "0.3"
regex     = "0.1"
