[package]
name = "muxed"
version = "0.7.0-development"
authors = ["Brian Pearce"]

[workspace]
members = [
    "common",
    "load",
    "new",
    "snapshot"
]

[dependencies]
common   = { path = "./common" }
load     = { path = "./load" }
new      = { path = "./new" }
snapshot = { path = "./snapshot" }
docopt   = "0.7"

[dev-dependencies]
dirs      = "1.0.5"
libc      = "0.2.21"
rand      = "0.3.15"
regex     = "0.2.1"
yaml-rust = { version = "0.3.2", default-features = false }
