[package]
name = "muxed"
version = "0.7.0"
authors = ["Brian Pearce"]

[dependencies]
dirs            = "1.0.5"
docopt          = "0.7"
libc            = "0.2.21"
regex           = "0.2.1"
rustc-serialize = "0.3"
serde           = "0.8.18"
serde_derive    = "0.8.18"
serde_yaml      = "0.5"
yaml-rust       = { version = "0.3.2", default-features = false }

[dev-dependencies]
rand      = "0.3.15"
