---
- hosts: all
  sudo: true
  tasks:
    - name: update apt-get
      apt: update_cache=yes

    - name: install required apt-get packages
      apt: name={{ item }} state=present force=yes
      with_items:
        - curl
        - git
        - autotools-dev
        - automake
        - cmake
        - clang

    #- name: uninstall apt-get packages
    #  apt: name={{ item }} state=absent force=yes
    #  with_items:
    #    - tmux

    - name: download rust installer
      get_url: url=https://static.rust-lang.org/rustup.sh dest=/usr/bin/rustup mode=a+x validate_certs=no

    - name: install rust
      command: rustup #--yes
      sudo: no
