[package]
name = "muxedsnapshot"
version = "0.1.0"
authors = ["Brian Pearce"]

[dependencies]
libc         = "0.2.10"
yaml-rust    = "0.3.2"
regex        = "0.1"
clap         = "2.9.2"
serde        = "0.8.18"
serde_derive = "0.8.18"
serde_yaml   = "0.5"

[dev-dependencies]
rand = "0.3"
