---
name: tests

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  test:
    strategy:
      matrix:
        tmux_version: [3.5a, master]
    name: unit tests
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - uses: swatinem/rust-cache@v2.7.5

      - name: unit tests
        run: cargo test --all --lib

  integration-tests:
    strategy:
      matrix:
        tmux_version: [3.5a]
        os: [ubuntu-latest, macos-latest]
    name: integration tests
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.tmux_version == 'master' }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - uses: swatinem/rust-cache@v2.7.5

      - name: build tmux
        run: ./scripts/build_tmux.sh ${{ matrix.tmux_version }}
      - name: integration tests
        run: cargo test --all --test '*'